version: "3.9"
services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: forumhub-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
